export * from "./database";

// Re-export commonly used types at the top level
export type {
  Product,
  ProductWithCategory,
  ProductDetail,
  Cart,
  CartItem,
  CartItemExpanded,
  Order,
  OrderItem,
  OrderWithItems,
  UserProfile,
  UserAddress,
  Category,
  ProductVariant,
  ProductImage,
  UserRole,
  OrderStatus,
  PaymentStatus,
  ShippingAddress,
  ProcessOrderRequest,
  ProcessOrderResponse,
  SyncCartRequest,
  SyncCartResponse,
  HeroBanner,
  HeroSlide,
  HeroSlideCta,
  HeroBannerWithSlides,
  HeroSlideWithCtas,
  SiteAnnouncement,
  BannerMediaType,
  BannerTransition,
  CtaVariant,
} from "./database";
